name: prebuild
on: {push: {branches: [master]}}
defaults:
  run:
    working-directory: repo
jobs:
  prebuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: { path: repo }
    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: install
      run: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y
        cargo install --git https://github.com/adaszko/complgen --tag v0.4.0 complgen
        
    - name: build
      run: |
        make

    - name: push
      run: |
        rm -rf .git
        git init -b prebuilt
        git config user.name 'GitHub Actions'
        git config user.email '224759579+quasipoint@users.noreply.github.com'
        git add -f dspace.bash dspace.zsh dspace.fish
        git commit -m 'Make prebuilt scripts ready for deploy'
        git push --force 'https://quasipoint:${{ github.token }}@github.com/${{ github.repository }}' prebuilt

